###
POST  http://localhost:8000/auth/register
Content-Type: application/json

{
  "first_name": "Tiffany",
  "last_name": "Nyawira",
  "username": "Tyla",
  "password": "password1",
  "email": "mwanikitiffany@gmail.com",
  "contact_phone": "+1-789-000-6678",
  "address": "227 Downtown ",
  "role": "admin",
  "image_url": "https://th.bing.com/th?id=OIF.Dr%2f2Lx7%2bPcSggxMsUv06gQ&w=202&h=202&c=7&r=0&o=5&pid=1.7"
}



###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "Tyla",
    "password": "password1"
}

###
POST  http://localhost:8000/auth/login
Content-Type: application/json

{
    "username": "Tiff",
    "password": "password"
}

###
GET  http://localhost:8000/users
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbmRyZXdfam9obiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcxMzgyNn0.6TI7YJWgc5higOJ2SG0oBwODOfo7-mmHFgqp9uA2-OE

###
POST  http://localhost:8000/user

Content-Type: application/json
{
  "first_name": "AJ",
  "last_name": "jackson",
  "email": "john.doe1234@example.com",
  "contact_phone": "+1234567890",
  "address": "123 Main St, Anytown, USA",
  "role": "user"
}



###
GET  http://localhost:8000/user/8

###
PUT  http://localhost:8000/update-user/8
Content-Type: application/json

{
  "first_name": "Andrew",
  "last_name": "john",
  "username": "Andrew_john",
  "password": "securepassword123",
  "email": "Andrew229999@example.com",
  "contact_phone": "1234567890",
  "address": "123 Main St",
  "role": "admin"
}

###

DELETE http://localhost:8000/delete-user/1

###
GET http://localhost:8000/specifications

###
POST http://localhost:8000/specification
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKYXkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjEyMjUxMDF9.3LMt-5yiX-Y3aeyn8H2Eum8oRDE3OTCxBLhIOlm-YZM


###
GET http://localhost:8000/specification/1

###
PUT http://localhost:8000/specification/1
{
  "manufacturer": "Toyota",
  "model": "Camry",
  "year": 2020,
  "fuel_type": "Petrol",
  "engine_capacity": 1800,
  "transmission": "Automatic",
  "seating_capacity": 5,
  "color": "Red",
  "features": "Air Conditioning, Bluetooth, Backup Camera, Power Steering"
}

###
POST http://localhost:8000/specification
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUeWxhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIxMzAwMzgwfQ.bcXqo_eyin7laghZCQMyP1McGhGirgf3wYjgrdE6v4I
Content-Type: application/json

  {
    "manufacturer": "Tesla",
    "model": "Model S",
    "year": 2022,
    "fuel_type": "Electric",
    "engine_capacity": 0,
    "transmission": "Automatic",
    "seating_capacity": 5,
    "color": "White",
    "features": "Air Conditioning, Bluetooth, Autopilot",
    "url_image": "https://www.tesla.com/sites/default/files/modelsx-new/social/model-s-hero-social.jpg"
  }













###
POST  http://localhost:8000/vehicle
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUeWxhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIxMzAwMzgwfQ.bcXqo_eyin7laghZCQMyP1McGhGirgf3wYjgrdE6v4I
Content-Type: application/json

{
  "vehicleSpec_id": 4,
  "rental_rate": 6700,
  "availability": true
}







###
GET  http://localhost:8000/vehicles
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbmRyZXdfam9obiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcxMzgyNn0.6TI7YJWgc5higOJ2SG0oBwODOfo7-mmHFgqp9uA2-OE


### 
GET  http://localhost:8000/vehicle/1

PUT  http://localhost:8000/update-vehicle/1

###
DELETE  http://localhost:8000/delete-vehicle/1

###  
GET  http://localhost:8000/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbmRyZXdfam9obiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDM5MDA1Nn0.mTBN9AOQGaYwYeAknTCVSOCkgVB7F2V1x0ug8vE7j6Y

###
POST http://localhost:8000/location
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJKYXkiLCJyb2xlIjoiYWRtaW4iLCJleHAiOjE3MjEyMjUxMDF9.3LMt-5yiX-Y3aeyn8H2Eum8oRDE3OTCxBLhIOlm-YZM
Content-Type: application/json

{
  "name": "Spruce Street",
  "address": "456 Spruce Street",
  "contact_phone": "+1-567-8901"
}










###
POST http://localhost:8000/location
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUeWxhIiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNzIxMzAwMzgwfQ.bcXqo_eyin7laghZCQMyP1McGhGirgf3wYjgrdE6v4I
Content-Type: application/json

{
  "name": "Birch Avenue",
  "address": "678 Birch Avenue",
  "contact_phone": "+1-901-2345"
}








###
GET http://localhost:8000/locations
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbmRyZXdfam9obiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcxMzgyNn0.6TI7YJWgc5higOJ2SG0oBwODOfo7-mmHFgqp9uA2-OE


PUT http://localhost:8000/update-location/3
Content-Type: application/json

{
  "location_id": 6,
  "name": "Achivers ",
  "address": "Two Rivers",
  "contact_phone": "+1-566-4128"
}

DELETE http://localhost:8000/delete-location/3


### user bookings
GET  http://localhost:8000/user-bookings/7
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUaWZmIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjEwNTUyNTd9.YZl2p3__64R4RZj0KcttXEhfsXfmBbrX2mhClfnFf1A

### 
PUT   http://localhost:8000/update-booking/20
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUaWZmIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjEwNTUyNTd9.YZl2p3__64R4RZj0KcttXEhfsXfmBbrX2mhClfnFf1A
Content-Type: application/json

  {
    "booking_id": 20,
    "user_id": 7,
    "vehicle_id": 3,
    "location_id": 6,
    "booking_date": "2024-06-15",
    "return_date": "2024-07-17",
    "total_amount": 10000.00,
    "booking_status": "Pending"
  }

###
GET http://localhost:8000/bookings
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBbmRyZXdfam9obiIsInJvbGUiOiJhZG1pbiIsImV4cCI6MTcyMDcxMzgyNn0.6TI7YJWgc5higOJ2SG0oBwODOfo7-mmHFgqp9uA2-OE

###
GET http://localhost:8000/tickets
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUaWZmIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MTU4MDl9.8fYGwh6phmZnlz8rRa5UvgDP2pdKmjLoGlKpIofhQ7k

###
POST http://localhost:8000/ticket
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUaWZmIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MTU4MDl9.8fYGwh6phmZnlz8rRa5UvgDP2pdKmjLoGlKpIofhQ7k
Content-Type: application/json

{
  "user_id":6,
  "subject": "Damages",
  "description":" Damaged Vehicle",
  "ticket_status": "Open"
}

###
GET http://localhost:8000/payments
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUaWZmIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MTU4MDl9.8fYGwh6phmZnlz8rRa5UvgDP2pdKmjLoGlKpIofhQ7k


###
POST http://localhost:8000/payment
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJUaWZmIiwicm9sZSI6InVzZXIiLCJleHAiOjE3MjA3MTU4MDl9.8fYGwh6phmZnlz8rRa5UvgDP2pdKmjLoGlKpIofhQ7k
Content-Type: application/json

{
  "user_id":7,
  "booking_id":20,
  "amount": 5000,
  "payment_status": "Pending",
  "payment_date":"2024-07-12T06:48:00.000Z",
  "payment_method":"card",
  "transaction_id": 1
}